services:
  - type: web
    name: telegram-ema-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
